/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildlifeRouteImport } from './routes/wildlife'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SimbaRouteImport } from './routes/simba'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as MapRouteImport } from './routes/map'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as ExpansionRouteImport } from './routes/expansion'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as OperatorWildlifeRouteImport } from './routes/operator.wildlife'
import { Route as OperatorSettingsRouteImport } from './routes/operator.settings'
import { Route as OperatorPayoutsRouteImport } from './routes/operator.payouts'
import { Route as OperatorListingsRouteImport } from './routes/operator.listings'
import { Route as OperatorBookingsRouteImport } from './routes/operator.bookings'
import { Route as OperatorAnalyticsRouteImport } from './routes/operator.analytics'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as OperatorListingsNewRouteImport } from './routes/operator.listings.new'
import { Route as OperatorListingsIdEditRouteImport } from './routes/operator.listings.$id.edit'

const WildlifeRoute = WildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SimbaRoute = SimbaRouteImport.update({
  id: '/simba',
  path: '/simba',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpansionRoute = ExpansionRouteImport.update({
  id: '/expansion',
  path: '/expansion',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const OperatorWildlifeRoute = OperatorWildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorSettingsRoute = OperatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPayoutsRoute = OperatorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorListingsRoute = OperatorListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorBookingsRoute = OperatorBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAnalyticsRoute = OperatorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OperatorRoute,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/$hotelId',
  path: '/$hotelId',
  getParentRoute: () => HotelsRoute,
} as any)
const OperatorListingsNewRoute = OperatorListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OperatorListingsRoute,
} as any)
const OperatorListingsIdEditRoute = OperatorListingsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => OperatorListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/expansion': typeof ExpansionRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/icons': typeof IconsRoute
  '/intelligence': typeof IntelligenceRoute
  '/map': typeof MapRoute
  '/operator': typeof OperatorRouteWithChildren
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/simba': typeof SimbaRoute
  '/stories': typeof StoriesRouteWithChildren
  '/support': typeof SupportRoute
  '/wildlife': typeof WildlifeRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/bookings': typeof OperatorBookingsRoute
  '/operator/listings': typeof OperatorListingsRouteWithChildren
  '/operator/payouts': typeof OperatorPayoutsRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/wildlife': typeof OperatorWildlifeRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/operator/': typeof OperatorIndexRoute
  '/operator/listings/new': typeof OperatorListingsNewRoute
  '/operator/listings/$id/edit': typeof OperatorListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/expansion': typeof ExpansionRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/icons': typeof IconsRoute
  '/intelligence': typeof IntelligenceRoute
  '/map': typeof MapRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/simba': typeof SimbaRoute
  '/stories': typeof StoriesRouteWithChildren
  '/support': typeof SupportRoute
  '/wildlife': typeof WildlifeRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/bookings': typeof OperatorBookingsRoute
  '/operator/listings': typeof OperatorListingsRouteWithChildren
  '/operator/payouts': typeof OperatorPayoutsRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/wildlife': typeof OperatorWildlifeRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/operator': typeof OperatorIndexRoute
  '/operator/listings/new': typeof OperatorListingsNewRoute
  '/operator/listings/$id/edit': typeof OperatorListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/expansion': typeof ExpansionRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/icons': typeof IconsRoute
  '/intelligence': typeof IntelligenceRoute
  '/map': typeof MapRoute
  '/operator': typeof OperatorRouteWithChildren
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/simba': typeof SimbaRoute
  '/stories': typeof StoriesRouteWithChildren
  '/support': typeof SupportRoute
  '/wildlife': typeof WildlifeRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/bookings': typeof OperatorBookingsRoute
  '/operator/listings': typeof OperatorListingsRouteWithChildren
  '/operator/payouts': typeof OperatorPayoutsRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/wildlife': typeof OperatorWildlifeRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/operator/': typeof OperatorIndexRoute
  '/operator/listings/new': typeof OperatorListingsNewRoute
  '/operator/listings/$id/edit': typeof OperatorListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/expansion'
    | '/hotels'
    | '/icons'
    | '/intelligence'
    | '/map'
    | '/operator'
    | '/partner'
    | '/plan'
    | '/profile'
    | '/simba'
    | '/stories'
    | '/support'
    | '/wildlife'
    | '/hotels/$hotelId'
    | '/operator/analytics'
    | '/operator/bookings'
    | '/operator/listings'
    | '/operator/payouts'
    | '/operator/settings'
    | '/operator/wildlife'
    | '/stories/$slug'
    | '/operator/'
    | '/operator/listings/new'
    | '/operator/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/expansion'
    | '/hotels'
    | '/icons'
    | '/intelligence'
    | '/map'
    | '/partner'
    | '/plan'
    | '/profile'
    | '/simba'
    | '/stories'
    | '/support'
    | '/wildlife'
    | '/hotels/$hotelId'
    | '/operator/analytics'
    | '/operator/bookings'
    | '/operator/listings'
    | '/operator/payouts'
    | '/operator/settings'
    | '/operator/wildlife'
    | '/stories/$slug'
    | '/operator'
    | '/operator/listings/new'
    | '/operator/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/book'
    | '/expansion'
    | '/hotels'
    | '/icons'
    | '/intelligence'
    | '/map'
    | '/operator'
    | '/partner'
    | '/plan'
    | '/profile'
    | '/simba'
    | '/stories'
    | '/support'
    | '/wildlife'
    | '/hotels/$hotelId'
    | '/operator/analytics'
    | '/operator/bookings'
    | '/operator/listings'
    | '/operator/payouts'
    | '/operator/settings'
    | '/operator/wildlife'
    | '/stories/$slug'
    | '/operator/'
    | '/operator/listings/new'
    | '/operator/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ExpansionRoute: typeof ExpansionRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  IconsRoute: typeof IconsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  MapRoute: typeof MapRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  PartnerRoute: typeof PartnerRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  SimbaRoute: typeof SimbaRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  SupportRoute: typeof SupportRoute
  WildlifeRoute: typeof WildlifeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wildlife': {
      id: '/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof WildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simba': {
      id: '/simba'
      path: '/simba'
      fullPath: '/simba'
      preLoaderRoute: typeof SimbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expansion': {
      id: '/expansion'
      path: '/expansion'
      fullPath: '/expansion'
      preLoaderRoute: typeof ExpansionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/operator/wildlife': {
      id: '/operator/wildlife'
      path: '/wildlife'
      fullPath: '/operator/wildlife'
      preLoaderRoute: typeof OperatorWildlifeRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/settings': {
      id: '/operator/settings'
      path: '/settings'
      fullPath: '/operator/settings'
      preLoaderRoute: typeof OperatorSettingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/payouts': {
      id: '/operator/payouts'
      path: '/payouts'
      fullPath: '/operator/payouts'
      preLoaderRoute: typeof OperatorPayoutsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/listings': {
      id: '/operator/listings'
      path: '/listings'
      fullPath: '/operator/listings'
      preLoaderRoute: typeof OperatorListingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/bookings': {
      id: '/operator/bookings'
      path: '/bookings'
      fullPath: '/operator/bookings'
      preLoaderRoute: typeof OperatorBookingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/analytics': {
      id: '/operator/analytics'
      path: '/analytics'
      fullPath: '/operator/analytics'
      preLoaderRoute: typeof OperatorAnalyticsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/operator/listings/new': {
      id: '/operator/listings/new'
      path: '/new'
      fullPath: '/operator/listings/new'
      preLoaderRoute: typeof OperatorListingsNewRouteImport
      parentRoute: typeof OperatorListingsRoute
    }
    '/operator/listings/$id/edit': {
      id: '/operator/listings/$id/edit'
      path: '/$id/edit'
      fullPath: '/operator/listings/$id/edit'
      preLoaderRoute: typeof OperatorListingsIdEditRouteImport
      parentRoute: typeof OperatorListingsRoute
    }
  }
}

interface HotelsRouteChildren {
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsHotelIdRoute: HotelsHotelIdRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

interface OperatorListingsRouteChildren {
  OperatorListingsNewRoute: typeof OperatorListingsNewRoute
  OperatorListingsIdEditRoute: typeof OperatorListingsIdEditRoute
}

const OperatorListingsRouteChildren: OperatorListingsRouteChildren = {
  OperatorListingsNewRoute: OperatorListingsNewRoute,
  OperatorListingsIdEditRoute: OperatorListingsIdEditRoute,
}

const OperatorListingsRouteWithChildren =
  OperatorListingsRoute._addFileChildren(OperatorListingsRouteChildren)

interface OperatorRouteChildren {
  OperatorAnalyticsRoute: typeof OperatorAnalyticsRoute
  OperatorBookingsRoute: typeof OperatorBookingsRoute
  OperatorListingsRoute: typeof OperatorListingsRouteWithChildren
  OperatorPayoutsRoute: typeof OperatorPayoutsRoute
  OperatorSettingsRoute: typeof OperatorSettingsRoute
  OperatorWildlifeRoute: typeof OperatorWildlifeRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAnalyticsRoute: OperatorAnalyticsRoute,
  OperatorBookingsRoute: OperatorBookingsRoute,
  OperatorListingsRoute: OperatorListingsRouteWithChildren,
  OperatorPayoutsRoute: OperatorPayoutsRoute,
  OperatorSettingsRoute: OperatorSettingsRoute,
  OperatorWildlifeRoute: OperatorWildlifeRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ExpansionRoute: ExpansionRoute,
  HotelsRoute: HotelsRouteWithChildren,
  IconsRoute: IconsRoute,
  IntelligenceRoute: IntelligenceRoute,
  MapRoute: MapRoute,
  OperatorRoute: OperatorRouteWithChildren,
  PartnerRoute: PartnerRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  SimbaRoute: SimbaRoute,
  StoriesRoute: StoriesRouteWithChildren,
  SupportRoute: SupportRoute,
  WildlifeRoute: WildlifeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
